# ╔══════════════════════════════════════════════════════════════╗
# ║  EVE-PRIME — Debug & Crash Configuration                     ║
# ║  Sourced by hyprland.conf                                    ║
# ╚══════════════════════════════════════════════════════════════╝

debug {
    disable_logs = false
    enable_stdout_logs = false
    damage_tracking = 2
    disable_time = false
    error_position = 0
    colored_stdout_logs = true
}
