
# ╔══════════════════════════════════════════════════════════════╗
# ║         EVE-PRIME — DECORATION                               ║
# ║         Glass void aesthetic — blur, shadows, opacity        ║
# ║         Per-window opacity in windowrules.conf               ║
# ╚══════════════════════════════════════════════════════════════╝

decoration {
    rounding = 10

    active_opacity   = 1.0
    inactive_opacity = 1.0

    blur {
        enabled           = true
        size              = 6
        passes            = 3
        new_optimizations = true
        xray              = false
        noise             = 0.0117
        contrast          = 0.8916
        brightness        = 0.8
        vibrancy          = 0.1696
        vibrancy_darkness = 0.0
        special           = true
        popups            = true
    }

    shadow {
        enabled      = true
        range        = 20
        render_power = 3
        color        = rgba(7B2FBE55)
        ignore_window = true
    }

    dim_inactive = true
    dim_strength = 0.12
    dim_special  = 0.3
}
