# ╔══════════════════════════════════════════════════════════════╗
# ║         EVE-PRIME — HYPRLAND MASTER CONFIG                   ║
# ║         This file sources everything. Touch nothing here.    ║
# ╚══════════════════════════════════════════════════════════════╝

# ── VARIABLES — apps and paths ─────────────────────────────────
$mainMod   = SUPER
$terminal  = kitty
$browser   = firefox
$files     = thunar
$menu      = wofi --show drun
$wallpaper = ~/.config/hypr/scripts/omni_wall.sh

# ── SOURCE ORDER MATTERS ────────────────────────────────────────
source = ~/.config/hypr/themes/colors.conf       # color engine first
source = ~/.config/hypr/debug.conf
source = ~/.config/hypr/env.conf                 # wayland environment
source = ~/.config/hypr/monitors.conf            # display setup
source = ~/.config/hypr/autostart.conf           # launch services
source = ~/.config/hypr/input.conf               # keyboard and mouse
source = ~/.config/hypr/general.conf             # gaps, borders, layout
source = ~/.config/hypr/decoration.conf          # glass, blur, shadows
source = ~/.config/hypr/animations.conf          # motion and transitions
source = ~/.config/hypr/plugins.conf             # hyprexpo and others
source = ~/.config/hypr/keybinds.conf            # all keybindings
source = ~/.config/hypr/windowrules.conf         # per-app rules
source = ~/.config/hypr/userprefs.conf           # user overrides last
