# ╔══════════════════════════════════════════════════════════════╗
# ║         EVE-PRIME — INPUT                                    ║
# ║         Keyboard, mouse, sensitivity                         ║
# ╚══════════════════════════════════════════════════════════════╝

input {
    kb_layout     = us
    kb_options    = caps:escape   # caps lock acts as escape
    follow_mouse  = 1
    mouse_refocus = true
    float_switch_override_focus = 2
    sensitivity   = 0             # 0 = no modification
    accel_profile = flat          # no mouse acceleration
    force_no_accel = 1

    touchpad {
        natural_scroll = true
        tap-to-click   = true
        drag_lock      = true
        scroll_factor  = 0.8
    }
}

cursor {
    no_hardware_cursors = true
    inactive_timeout    = 5
}
