#!/usr/bin/env bash
# ╔══════════════════════════════════════════════════════════════╗
# ║  EVE-PRIME — HEARTBEAT                                      ║
# ║  Pywal color extraction + Waybar reload + mpvpaper IPC      ║
# ║  Called by spectrum_picker on every wallpaper switch        ║
# ╚══════════════════════════════════════════════════════════════╝
set -euo pipefail

# ═══════════════════════════════════════════
# CONFIGURATION
# ═══════════════════════════════════════════
readonly CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/eve-prime"
readonly TMP_IMG="${CACHE_DIR}/anchor_frame.jpg"
readonly LOG_FILE="${CACHE_DIR}/heartbeat.log"
readonly LOCK_FILE="${CACHE_DIR}/heartbeat.lock"
readonly COLORS_SH="${HOME}/.cache/wallust/colors.sh"
readonly WAYBAR_STYLE="${HOME}/.config/waybar/style.css"
readonly WAYBAR_COLORS="${HOME}/.cache/eve-prime/waybar-colors.css"
readonly SEEK_SECONDS=2

# ═══════════════════════════════════════════
# LOGGING
# ═══════════════════════════════════════════
_log() {
    local level="$1"; shift
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] [${level}] $*" | tee -a "$LOG_FILE"
}

_rotate_log() {
    if [[ -f "$LOG_FILE" ]] && [[ $(wc -l < "$LOG_FILE") -gt 500 ]]; then
        tail -n 500 "$LOG_FILE" > "${LOG_FILE}.tmp" && mv "${LOG_FILE}.tmp" "$LOG_FILE"
    fi
}

# ═══════════════════════════════════════════
# LOCK GUARD
# ═══════════════════════════════════════════
_acquire_lock() {
    if [[ -f "$LOCK_FILE" ]]; then
        local pid
        pid=$(<"$LOCK_FILE")
        if kill -0 "$pid" 2>/dev/null; then
            _log "WARN" "Already running (PID ${pid}). Aborting."
            exit 0
        fi
        rm -f "$LOCK_FILE"
    fi
    echo $$ > "$LOCK_FILE"
}

_cleanup() {
    rm -f "$LOCK_FILE"
}
trap _cleanup EXIT

# ═══════════════════════════════════════════
# FRAME EXTRACTION
# ═══════════════════════════════════════════
_extract_frame() {
    local video="$1"
    _log "INFO" "Extracting frame from: $(basename "$video")"
    ffmpeg -y \
        -ss "${SEEK_SECONDS}" \
        -i "$video" \
        -vframes 1 \
        -q:v 2 \
        -pix_fmt yuvj420p \
        "$TMP_IMG" \
        -loglevel error 2>>"$LOG_FILE" || {
        _log "ERROR" "ffmpeg failed on: $video"
        exit 1
    }
    [[ -s "$TMP_IMG" ]] || { _log "ERROR" "Frame file empty: ${TMP_IMG}"; exit 1; }
}

# ═══════════════════════════════════════════
# WALLUST COLOR EXTRACTION
# ═══════════════════════════════════════════
_run_wallust() {
    _log "INFO" "Running wallust..."
    command -v wallust &>/dev/null || { _log "WARN" "wallust not installed — skipping colors"; return 0; }
    wallust run "$TMP_IMG" --quiet 2>>"$LOG_FILE" || { _log "ERROR" "wallust failed"; exit 1; }
    [[ -f "$COLORS_SH" ]] || { _log "ERROR" "wallust produced no colors.sh"; exit 1; }
}

# ═══════════════════════════════════════════
# APPLY BORDER SPECTRUM
# ═══════════════════════════════════════════
_apply_spectrum() {
    [[ -f "$COLORS_SH" ]] || return 0

    # shellcheck disable=SC1090
    source "$COLORS_SH"

    local B1="${color1:-88c0d0}"
    local B2="${color4:-b48ead}"
    local B3="${color6:-81a1c1}"
    B1="${B1/\#/}ff"
    B2="${B2/\#/}ff"
    B3="${B3/\#/}ff"

    local cmd="rgba(${B1}) rgba(${B2}) rgba(${B3}) 45deg"
    hyprctl keyword general:col.active_border "${cmd}" >/dev/null 2>>"$LOG_FILE" || true
    _log "INFO" "Spectrum applied: ${cmd}"
}

# ═══════════════════════════════════════════
# WAYBAR CSS COLORS
# ═══════════════════════════════════════════
_write_waybar_colors() {
    [[ -f "$COLORS_SH" ]] || return 0
    # shellcheck disable=SC1090
    source "$COLORS_SH"

    mkdir -p "$(dirname "$WAYBAR_COLORS")"
    cat > "$WAYBAR_COLORS" << EOF
/* EVE-PRIME — auto-generated by heartbeat.sh — do not edit */
@define-color eve-accent   ${color4:-#88c0d0};
@define-color eve-accent2  ${color1:-#b48ead};
@define-color eve-accent3  ${color6:-#81a1c1};
@define-color eve-bg       ${color0:-#0d0d1a};
@define-color eve-fg       ${color7:-#eceff4};
EOF
    _log "INFO" "Waybar colors written: ${WAYBAR_COLORS}"

    # Reload waybar if running
    pkill -SIGUSR2 waybar 2>/dev/null || true
}

# ═══════════════════════════════════════════
# MPVPAPER IPC — FORCE UNPAUSE
# Prevents wallpaper freeze during hyprexpo overview
# ═══════════════════════════════════════════
_mpvpaper_unpause() {
    local socket
    # mpvpaper creates socket at /tmp/mpvpaper.sock or /tmp/mpvsocket
    for socket in /tmp/mpvpaper.sock /tmp/mpvsocket /tmp/mpv-socket; do
        if [[ -S "$socket" ]]; then
            echo '{"command":["set_property","pause",false]}' | \
                socat - "UNIX-CONNECT:${socket}" >/dev/null 2>&1 || true
            _log "INFO" "mpvpaper unpaused via ${socket}"
            return 0
        fi
    done

    # Fallback: find socket from mpvpaper process
    local pid
    pid=$(pgrep -x mpvpaper 2>/dev/null | head -1) || true
    if [[ -n "$pid" ]]; then
        local proc_socket="/proc/${pid}/fd"
        socket=$(ls -la "$proc_socket" 2>/dev/null | grep -oP '/tmp/[^\s]+\.sock' | head -1) || true
        if [[ -n "$socket" && -S "$socket" ]]; then
            echo '{"command":["set_property","pause",false]}' | \
                socat - "UNIX-CONNECT:${socket}" >/dev/null 2>&1 || true
            _log "INFO" "mpvpaper unpaused via proc socket: ${socket}"
        fi
    fi
}

# ═══════════════════════════════════════════
# MAIN
# ═══════════════════════════════════════════
main() {
    local video="${1:-}"
    [[ -z "$video" ]] && { echo "Usage: heartbeat.sh <video_path>"; exit 1; }
    [[ -f "$video" ]] || { _log "ERROR" "Video not found: ${video}"; exit 1; }

    mkdir -p "$CACHE_DIR"
    _rotate_log
    _acquire_lock

    _log "INFO" "=== Heartbeat start: $(basename "$video") ==="
    _extract_frame "$video"
    _run_wallust
    _apply_spectrum
    _write_waybar_colors
    _mpvpaper_unpause
    _log "INFO" "=== Heartbeat complete ==="
}

main "$@"
